### ISSUE TITLE
ScanControlDriver initialization failed

### ISSUE THREAD

**Issue by Inkinenantti** [sam-xl/scancontrol#2] opened 2019-12-16 09:44 UTC
I can't make the connection to the scanner. When I roslaunch scancontrol driver.launch, it will crash and give me following message in the terminal:

```
[ INFO] [1576489010.347079901]: There is 1 scanCONTROL device connected.
[ INFO] [1576489010.350253697]: Interface found: MICRO-EPSILON Optronic GmbH-scanCONTROL 2950-25 -214020017
[FATAL] [1576489010.350391057]: Error while connecting to device! Code: -302
[ INFO] [1576489010.350487346]: ScanControlDriver initialization failed.
[scancontrol_1-1] process has died [pid 8856, exit code -11,cmd /home/inkyfiny888/Documents/SMR-Fokker-assignment/catkin_ws/devel/lib/scancontrol/driver_node __name:=scancontrol_1 __log:=/home/inkyfiny888/.ros/log/7a395022-1fe7-11ea-9b8b-00e04c361302/scancontrol_1-1.log].
log file: /home/inkyfiny888/.ros/log/7a395022-1fe7-11ea-9b8b-00e04c361302/scancontrol_1-1*.log
[FATAL] [1576489017.786317]: Failed to find scanCONTROL services. Make sure the scancontrol node is up and running.
PluginManager._load_plugin() could not load plugin "scancontrol/gui":
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 102, in load
    self._load()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 101, in load
    return class_ref(plugin_context)
  File "/home/inkyfiny888/Documents/SMR-Fokker-assignment/catkin_ws/src/scancontrol-master/scancontrol/src/scancontrol/gui.py", line 62, in __init__
    response = self.get_feature(self.ID_SCANNER_TYPE)
AttributeError: 'ScanControlGui' object has no attribute 'get_feature
```

**Comment by rtonnaer** [comment] 2019-12-16 10:25
[C++-Linux-InterfaceDocumentation.pdf](https://github.com/sam-xl/scancontrol/files/3967479/C%2B%2B-Linux-InterfaceDocumentation.pdf)

Please check out this document for the error codes for the SDK. -302 apparently means that this sensor is already connected.

Maybe check if a terminal is running somewhere that has an active connection to the sensor.

**Comment by gavanderhoorn** [comment] 2019-12-16 10:28
> Please check out this document for the error codes for the SDK. -302 apparently means that this sensor is already connected.

might be a nice enhancement to print not just the numeric error code, but a human readable string as well.

> ```
> [FATAL] [1576489010.350391057]: Error while connecting to device! Code: -302
> [ INFO] [1576489010.350487346]: ScanControlDriver initialization failed.
> [scancontrol_1-1] process has died [pid 8856, exit code -11,
> ```

@dave992: if the connection error is `FATAL`, why does the driver binary then crash with a `SEGFAULT`?

**Comment by rtonnaer** [comment] 2019-12-16 10:28
Also no windows tools should be connected btw

**Comment by rtonnaer** [comment] 2019-12-16 10:36
I will add an issue to the repo with your suggestions Gijs, i want to try adding that functionality to the code.

**Comment by Inkinenantti** [comment] 2019-12-16 13:50
Possibly solved: connection was made with USB 2.0 to ethernet adapter. Sensor needs Gigabit-Ethernet to work proberly (usb 3.0).

**Comment by dave992** [comment] 2019-12-16 20:40
> [C++-Linux-InterfaceDocumentation.pdf](https://github.com/sam-xl/scancontrol/files/3967479/C%2B%2B-Linux-InterfaceDocumentation.pdf)
> 
> Please check out this document for the error codes for the SDK. -302 apparently means that this sensor is already connected.
> 
> Maybe check if a terminal is running somewhere that has an active connection to the sensor.

Note that this is the document for the 1.0 version of the SDK. For the 2.0 version (used by this repository): [C++-Linux-InterfaceDocumentation.pdf](https://github.com/sam-xl/scancontrol/files/3970009/C%2B%2B-Linux-InterfaceDocumentation.pdf)

**Comment by Inkinenantti** [comment] 2019-12-18 13:25
Upgraded to the USB 3.0 adapter. Scancontrol configuration tools - program started to work correctly, but problems with ros keeps happening.

**Comment by dave992** [comment] 2019-12-19 08:13
The driver depends on the Aravis library which I see has some additional instructions for USB based "cameras" regarding permissions. Have you tried the steps listed on the [Aravis GitHub page](https://github.com/AravisProject/aravis)? I'm not sure if it applies to a USB to Ethernet adapter, but it can't hurt to try.

**Comment by gavanderhoorn** [comment] 2019-12-19 08:18
USB devices use different ways of accessing them for read/write.

Eth-over-USB works differently and is seen as a regular NIC by userspace.

I doubt access permissions on the device file matter, as eth-over-usb is handled by the kernel, which has access to everything.

**Comment by Inkinenantti** [comment] 2019-12-20 13:08
I added permissions for usb-eth. but it didn't solve the problem.

**Comment by dave992** [comment] 2020-09-14 07:46
Closing this for now as we were unable to reproduce the issue.

**Closed by dave992** 2020-09-14 07:46 UTC
