### ISSUE TITLE
ScanControlDriver initialization failed

### ISSUE THREAD

**Issue by Inkinenantti** [sam-xl/scancontrol#6] opened 2019-12-18 13:17 UTC
I still can't make connection to the scanner. I upgraded the usb-ethernet adapter to usb 3.0 version and the Scancontrol configuration tools - program started to work correctly, but when I roslaunch scancontrol driver.launch, it will crash and give me following message in the terminal:

```
process[scancontrol_1-1]: started with pid [3672]
process[my_rqt_dashboard-2]: started with pid [3673]
[ INFO] [1576674066.951658927]: There is 1 scanCONTROL device connected.
[ INFO] [1576674066.952360733]: Interface found: MICRO-EPSILON Optronic GmbH-scanCONTROL 2950-25 -214020017
[FATAL] [1576674066.952389369]: Error while connecting to device! Code: -302
[ INFO] [1576674066.952413768]: ScanControlDriver initialization failed.
[scancontrol_1-1] process has died [pid 3672, exit code -11, cmd /home/inkyfiny888/Documents/SMR-Fokker-assignment/catkin_ws/devel/lib/scancontrol/driver_node __name:=scancontrol_1 __log:=/home/inkyfiny888/.ros/log/7821a00a-2195-11ea-b540-00e04c68029c/scancontrol_1-1.log].
log file: /home/inkyfiny888/.ros/log/7821a00a-2195-11ea-b540-00e04c68029c/scancontrol_1-1*.log
[FATAL] [1576674071.639370]: Failed to find scanCONTROL services. Make sure the scancontrol node is up and running.
PluginManager._load_plugin() could not load plugin "scancontrol/gui":
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 102, in load
    self._load()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 55, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 72, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 101, in load
    return class_ref(plugin_context)
  File "/home/inkyfiny888/Documents/SMR-Fokker-assignment/catkin_ws/src/scancontrol-master/scancontrol/src/scancontrol/gui.py", line 62, in __init__
    response = self.get_feature(self.ID_SCANNER_TYPE)
AttributeError: 'ScanControlGui' object has no attribute 'get_feature'
```

**Comment by gavanderhoorn** [comment] 2019-12-18 13:19
This looks like a duplicate of #2. Same error, same `SEGFAULT`.

Perhaps close this issue and re-open that one?

**Closed** 2019-12-18 13:24 UTC
